feat: erc20 sample chaincode contract
bestchains/fabric-builder-k8s pull request #2
Opened 2023-03-15 09:23 UTC by Lanture1064

temporally blocked minter verification

2023-03-15 09:36 UTC, bjwswang requested changes

2023-03-15 09:36 UTC, bjwswang commented on samples/erc20-sample/chaincode/token_contract.go
> +func (s *SmartContract) Initialize(ctx contractapi.TransactionContextInterface, name string, symbol string, decimals string) (bool, error) {
we can define a group of 
- owners(Orgs) who can mint/burn ERC20 tokens
during this initialization.
Means add a new argument `owners []string`

2023-03-15 09:36 UTC, bjwswang commented on samples/erc20-sample/chaincode/token_contract.go
> +	// if clientMSPID != "Org1MSP" {
check clientMspID is in `owners` list

2023-03-17 03:21 UTC, bjwswang commented on samples/erc20-sample/Dockerfile
> +FROM  172.22.50.223/bestchains-dev/golang:${GO_VER}-alpine${ALPINE_VER} as build
should use this dockerfile only when doning internal dev&test.

2023-03-17 03:47 UTC, bjwswang commented on samples/erc20-sample/chaincode/token_contract.go
> +	ownerComposite, err := ctx.GetStub().GetState(ownerCompositeKey)
Since this `check owner` function will be used at `mint` & `burn`,better to split this login into another function

2023-03-20 03:03 UTC, Lanture1064 commented
checkOwner() function split

2023-03-20 05:20 UTC, bjwswang commented on samples/erc20-sample/Dockerfile
> +FROM  172.22.50.223/bestchains-dev/golang:${GO_VER}-alpine${ALPINE_VER} as build
should use `FROM golang:${GO_VER}-alpine${ALPINE_VER} as build` instead of `172.22.50.223/bestchains-dev/golang`

2023-03-20 05:24 UTC, bjwswang commented on samples/erc20-sample/go.mod
> +go 1.17
use 
```
go 1.17

require github.com/hyperledger/fabric-contract-api-go v1.1.1

require (
	github.com/PuerkitoBio/purell v1.1.1 // indirect
	github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 // indirect
	github.com/go-openapi/jsonpointer v0.19.3 // indirect
	github.com/go-openapi/jsonreference v0.19.2 // indirect
	github.com/go-openapi/spec v0.19.4 // indirect
	github.com/go-openapi/swag v0.19.5 // indirect
	github.com/gobuffalo/envy v1.7.0 // indirect
	github.com/gobuffalo/packd v0.3.0 // indirect
	github.com/gobuffalo/packr v1.30.1 // indirect
	github.com/golang/protobuf v1.3.2 // indirect
	github.com/hyperledger/fabric-chaincode-go v0.0.0-20200424173110-d7076418f212 // indirect
	github.com/hyperledger/fabric-protos-go v0.0.0-20200424173316-dd554ba3746e // indirect
	github.com/joho/godotenv v1.3.0 // indirect
	github.com/mailru/easyjson v0.0.0-20190626092158-b2ccc519800e // indirect
	github.com/rogpeppe/go-internal v1.3.0 // indirect
	github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f // indirect
	github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415 // indirect
	github.com/xeipuuv/gojsonschema v1.2.0 // indirect
	golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297 // indirect
	golang.org/x/sys v0.0.0-20190710143415-6ec70d6a5542 // indirect
	golang.org/x/text v0.3.2 // indirect
	google.golang.org/genproto v0.0.0-20180831171423-11092d34479b // indirect
	google.golang.org/grpc v1.23.0 // indirect
	gopkg.in/yaml.v2 v2.2.8 // indirect
)

```

2023-03-20 05:26 UTC, bjwswang commented on samples/erc20-sample/chaincode/token_contract.go
> +			auth = true
`return true, nil` directly when check succ

2023-03-20 08:07 UTC, Lanture1064 commented
erc721 sample contract code modified & uploaded

2023-03-22 02:22 UTC, bjwswang approved these changes
/lgtm

@Lanture1064 good job!

2023-03-22 02:22 UTC, merged